version: '3'

services:

  api:
    container_name: "api"
    build:
      context: ./config/api
    working_dir: /var/www
    ports:
      - ${HOST_PORT_API}:9000
    volumes:
      - ${PATH_TO_API}:/var/www/
#      - ./config/api/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    environment:
      TZ: UTC

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    ports:
      - ${HOST_PORT_NGINX}:80
    volumes:
      - ${PATH_TO_API}:/var/www/api
      - ./.docker/nginx/log:/var/log/nginx
      - ./config/nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/admin.conf:/etc/nginx/conf.d/admin.conf
    environment:
      TZ: UTC
    depends_on:
      - api
      - site-api

  admin:
    container_name: "admin"
    image: node:16
    volumes:
      - ${PATH_TO_ADMIN}:/srv/www
    ports:
      - ${HOST_PORT_ADMIN}:9000 # для нормальной работы DEV-режима с обновлением через WS
    depends_on:
      - api
    working_dir: /srv/www
    command: bash -c "yarn dev"
    environment:
      TZ: UTC

  postgres:
    container_name: "postgresdb"
    image: postgres:15.2
    restart: always
    ports:
      - "${HOST_PORT_POSTGRES}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.docker/postgresql-data:/var/lib/postgresql/data

  redis:
    container_name: "redisdb"
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${HOST_PORT_REDIS}:6379"
    volumes:
      - ./.docker/redis-data:/data

  supervisord:
    container_name: "supervisord"
    build:
      context: ./config/supervisord
    volumes:
      - ${PATH_TO_API}:/var/www/
      - ./config/supervisord/conf.d:/etc/supervisord.d
    depends_on:
      - api

  site:
    container_name: "site"
    build:
      context: ./config/site
    volumes:
      - ${PATH_TO_SITE}:/srv/www
    ports:
      - ${HOST_PORT_SITE}:9000 # для нормальной работы DEV-режима с обновлением через WS
    depends_on:
      - site-api
    working_dir: /srv/www
    command: bash -c "npm run dev"
    environment:
      TZ: UTC

  site-api:
    container_name: "site-api"
    build:
      context: .
      dockerfile: ./config/site-api/Dockerfile
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      DB_SSLMODE: disable
      AWS_URL: https://storage.yandexcloud.net
      AWS_BUCKET: kidstyle72-dev
    ports:
      - ${HOST_PORT_SITE_API}:8080
    depends_on:
      - postgres
    restart: unless-stopped
