enum FileStatus {
  UPLOADING = 'UPLOADING',
  CREATED = 'CREATED',
  WAITING_QUEUE = 'WAITING_QUEUE',
  CONVERTING = 'CONVERTING',
  FINISHED = 'FINISHED',
  DELETED = 'DELETED',
  ERROR = 'ERROR',
}

export default FileStatus
